name = "worker-typescript-template"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "pnpm install && pnpm run build"
[build.upload]
format = "service-worker"
