name: Lint and test all changes

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Ensure code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2.3.3
      - name: Setup NodeJS environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm run lint
      - name: Run unit test
        run: pnpm run test
